### ISSUE TITLE
They're getting fancy with the text formatting

### ISSUE THREAD

**Issue by opti21** [callowcreation/banwannabefamousbots#1]
Ones i've seen lately look like this:
Wanna b̹eͣc̈́o̲me̬ f͇amou͊s? Bͣuy̻ f̫o͗llo͟wers, primes and viewe̬rs ̺oͤn (removed URL) ͇(̟bigfollows .com)!

**Comment by callowcreation** [comment]
This message will also be caught, thanks opti21.
const norm = message.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
That will replace the funky characters with 'normal' ones.

**Comment by opti21** [comment]
Nice!
